// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketExpress;

#nullable disable

namespace TicketExpress.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TicketExpress.Models.Boleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoComprador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventoIdId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComprador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoIdId");

                    b.ToTable("Boleto");
                });

            modelBuilder.Entity("TicketExpress.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PrecioBoleto")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("TicketExpress.Models.Boleto", b =>
                {
                    b.HasOne("TicketExpress.Models.Evento", "EventoId")
                        .WithMany()
                        .HasForeignKey("EventoIdId");

                    b.Navigation("EventoId");
                });
#pragma warning restore 612, 618
        }
    }
}
