// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketExpress;

#nullable disable

namespace TicketExpress.Migrations;

[DbContext(typeof(TicketExpressDbContext))]
[Migration("20260923022859_Inicial")]
partial class _20260923022859_Inicial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("TicketExpress.Models.Boleto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Cantidad")
                    .HasColumnType("INTEGER");

                b.Property<string>("CorreoComprador")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("EventoId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("FechaCompra")
                    .HasColumnType("TEXT");

                b.Property<string>("NombreComprador")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("EventoId");

                b.ToTable("Boletos");
            });

        modelBuilder.Entity("TicketExpress.Models.Evento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("CapacidadTotal")
                    .HasColumnType("INTEGER");

                b.Property<string>("Ciudad")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("TEXT");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("PrecioBoleto")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Eventos");
            });

        modelBuilder.Entity("TicketExpress.Models.Boleto", b =>
            {
                b.HasOne("TicketExpress.Models.Evento", "Evento")
                    .WithMany()
                    .HasForeignKey("EventoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Evento");
            });
#pragma warning restore 612, 618
    }
}
