// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketExpress;

#nullable disable

namespace TicketExpress.Migrations;

[DbContext(typeof(TicketExpressDbContext))]
partial class TicketExpressDbContextModelSnapshot : ModelSnapshot
{
    // If you encounter a merge conflict in the line below, it means you need to
    // discard one of the migration branches and recreate its migrations on top of
    // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
    public override string LastMigrationId => "20260923022859_Inicial";

    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("TicketExpress.Models.Boleto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Cantidad")
                    .HasColumnType("INTEGER");

                b.Property<string>("CorreoComprador")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("EventoId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("FechaCompra")
                    .HasColumnType("TEXT");

                b.Property<string>("NombreComprador")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("EventoId");

                b.ToTable("Boletos");
            });

        modelBuilder.Entity("TicketExpress.Models.Evento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("CapacidadTotal")
                    .HasColumnType("INTEGER");

                b.Property<string>("Ciudad")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("TEXT");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("PrecioBoleto")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Eventos");
            });

        modelBuilder.Entity("TicketExpress.Models.Boleto", b =>
            {
                b.HasOne("TicketExpress.Models.Evento", "Evento")
                    .WithMany()
                    .HasForeignKey("EventoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Evento");
            });
#pragma warning restore 612, 618
    }
}
