@TicketExpress_HostAddress = http://localhost:5208

GET {{TicketExpress_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{TicketExpress_HostAddress}}/weatherforecast/
Accept: application/json

###
